<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions targetNamespace="urn:CompositionTest" xmlns:apachesoap="http://xml.apache.org/xml-soap" xmlns:impl="urn:CompositionTest" xmlns:intf="urn:CompositionTest" xmlns:soapenc="http://schemas.xmlsoap.org/soap/encoding/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:wsdlsoap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
	<wsdl:message name="CompositionTestRequest">
		<wsdl:part name="ResidentSearchProfile" type="xsd:string"/>
	</wsdl:message>
	<wsdl:message name="CompositionTestResponse">
		<wsdl:part name="OutputLetter" type="xsd:string"/>
	</wsdl:message>
	<wsdl:portType name="CompositionTestPortType">
		<wsdl:operation name="CompositionTest" parameterOrder="ResidentSearchProfile">
			<wsdl:input message="impl:CompositionTestRequest" name="CompositionTestRequest"/>
			<wsdl:output message="impl:CompositionTestResponse" name="CompositionTestResponse"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="CompositionTestSoapBinding" type="impl:CompositionTestPortType">
		<wsdlsoap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="CompositionTest">
			<wsdlsoap:operation soapAction=""/>
			<wsdl:input name="CompositionTestRequest">
				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:CompositionTest" use="encoded"/>
			</wsdl:input>
			<wsdl:output name="CompositionTestResponse">
				<wsdlsoap:body encodingStyle="http://schemas.xmlsoap.org/soap/encoding/" namespace="urn:CompositionTest" use="encoded"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="CompositionTestService">
		<wsdl:port binding="impl:CompositionTestSoapBinding" name="CompositionTest">
			<wsdlsoap:address location="http://localhost:8080/PublicServices/CompositionTest"/>
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
